#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v12
# autospec commit: a5d3013
#
Name     : R-gbm
Version  : 2.2.2
Release  : 59
URL      : https://cran.r-project.org/src/contrib/gbm_2.2.2.tar.gz
Source0  : https://cran.r-project.org/src/contrib/gbm_2.2.2.tar.gz
Summary  : Generalized Boosted Regression Models
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-gbm-lib = %{version}-%{release}
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
algorithm and Friedman's gradient boosting machine. Includes regression 
  methods for least squares, absolute loss, t-distribution loss, quantile 
  regression, logistic, multinomial logistic, Poisson, Cox proportional hazards 
  partial likelihood, AdaBoost exponential loss, Huberized hinge loss, and 
  Learning to Rank measures (LambdaMart). Originally developed by Greg Ridgeway.
  Newer version available at github.com/gbm-developers/gbm3.

%package lib
Summary: lib components for the R-gbm package.
Group: Libraries

%description lib
lib components for the R-gbm package.


%prep
%setup -q -n gbm
pushd ..
cp -a gbm buildavx2
popd
pushd ..
cp -a gbm buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1719594726

%install
export SOURCE_DATE_EPOCH=1719594726
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/gbm/DESCRIPTION
/usr/lib64/R/library/gbm/INDEX
/usr/lib64/R/library/gbm/LICENSE
/usr/lib64/R/library/gbm/Meta/Rd.rds
/usr/lib64/R/library/gbm/Meta/demo.rds
/usr/lib64/R/library/gbm/Meta/features.rds
/usr/lib64/R/library/gbm/Meta/hsearch.rds
/usr/lib64/R/library/gbm/Meta/links.rds
/usr/lib64/R/library/gbm/Meta/nsInfo.rds
/usr/lib64/R/library/gbm/Meta/package.rds
/usr/lib64/R/library/gbm/Meta/vignette.rds
/usr/lib64/R/library/gbm/NAMESPACE
/usr/lib64/R/library/gbm/NEWS.md
/usr/lib64/R/library/gbm/R/gbm
/usr/lib64/R/library/gbm/R/gbm.rdb
/usr/lib64/R/library/gbm/R/gbm.rdx
/usr/lib64/R/library/gbm/demo/OOB-reps.R
/usr/lib64/R/library/gbm/demo/bernoulli.R
/usr/lib64/R/library/gbm/demo/coxph.R
/usr/lib64/R/library/gbm/demo/gaussian.R
/usr/lib64/R/library/gbm/demo/multinomial.R
/usr/lib64/R/library/gbm/demo/pairwise.R
/usr/lib64/R/library/gbm/demo/printExamples.R
/usr/lib64/R/library/gbm/demo/robustReg.R
/usr/lib64/R/library/gbm/doc/gbm.Rnw
/usr/lib64/R/library/gbm/doc/gbm.pdf
/usr/lib64/R/library/gbm/doc/index.html
/usr/lib64/R/library/gbm/help/AnIndex
/usr/lib64/R/library/gbm/help/aliases.rds
/usr/lib64/R/library/gbm/help/gbm.rdb
/usr/lib64/R/library/gbm/help/gbm.rdx
/usr/lib64/R/library/gbm/help/paths.rds
/usr/lib64/R/library/gbm/html/00Index.html
/usr/lib64/R/library/gbm/html/R.css
/usr/lib64/R/library/gbm/tests/tinytest.R
/usr/lib64/R/library/gbm/tinytest/test_bernoulli.R
/usr/lib64/R/library/gbm/tinytest/test_coxph.R
/usr/lib64/R/library/gbm/tinytest/test_least_squares.R
/usr/lib64/R/library/gbm/tinytest/test_relative_influence.R

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/gbm/libs/gbm.so
/V4/usr/lib64/R/library/gbm/libs/gbm.so
/usr/lib64/R/library/gbm/libs/gbm.so
